# Generated by Django 5.1.2 on 2025-06-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
